#define NEXTION_EVENT_RELEASE 0x00 
#define NEXTION_EVENT_PRESS 0x01

#define NEXTION_EVENT_LIMIT 8

#define NEXTION_LOOP_OK 1
#define NEXTION_LOOP_NULL 0
#define NEXTION_LOOP_NOEVENT -1

#define NEXTION_PAGE_ERROR -1
#define NEXTION_READ_ERROR 0
